import os

from PyQt4.QtCore import Qt, QDataStream, QIODevice, QFile
from PyQt4.QtGui import QPalette, QBrush, QColor, QApplication


def paletteFromFile(name):
    '''
    Helper function to read a palette from a binary palette file created with
    `paletteToFile()`
    :param name: filename, currently needs to be in the same directory
    :type name: str
    '''
    f = QFile(os.path.join(os.path.dirname(__file__), name + ".palette"))
    f.open(QIODevice.ReadOnly)
    ds = QDataStream(f)
    ds.setVersion(QDataStream.Qt_4_6)
    app = QApplication.instance()
    p = app.palette()
    ds >> p
    f.close()
    return p


def paletteToFile(path):
    '''
    Helper function to create a palette file from a running application.
    It will just dump the current QPalette as a binary stream.
    :type path: str
    '''
    w = QApplication.activeWindow()
    p = w.palette()
    f = QFile(path)
    f.open(QIODevice.WriteOnly)
    ds = QDataStream(f)
    ds.setVersion(QDataStream.Qt_4_6)
    ds << p
    f.close()


def standardPalette():
    '''
    Basic Nuke-like dark palette.
    '''
    palette = QPalette()
    brush = QBrush(QColor(255, 255, 255))
    brush.setStyle(Qt.SolidPattern)
    palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
    brush = QBrush(QColor(80, 80, 80))
    brush.setStyle(Qt.SolidPattern)
    palette.setBrush(QPalette.Active, QPalette.Button, brush)
    brush = QBrush(QColor(75, 75, 75))
    brush.setStyle(Qt.SolidPattern)
    palette.setBrush(QPalette.Active, QPalette.Light, brush)
    brush = QBrush(QColor(62, 62, 62))
    brush.setStyle(Qt.SolidPattern)
    palette.setBrush(QPalette.Active, QPalette.Midlight, brush)
    brush = QBrush(QColor(25, 25, 25))
    brush.setStyle(Qt.SolidPattern)
    palette.setBrush(QPalette.Active, QPalette.Dark, brush)
    brush = QBrush(QColor(33, 33, 33))
    brush.setStyle(Qt.SolidPattern)
    palette.setBrush(QPalette.Active, QPalette.Mid, brush)
    brush = QBrush(QColor(245, 245, 245))
    brush.setStyle(Qt.SolidPattern)
    palette.setBrush(QPalette.Active, QPalette.Text, brush)
    brush = QBrush(QColor(255, 255, 255))
    brush.setStyle(Qt.SolidPattern)
    palette.setBrush(QPalette.Active, QPalette.BrightText, brush)
    brush = QBrush(QColor(255, 255, 255))
    brush.setStyle(Qt.SolidPattern)
    palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
    brush = QBrush(QColor(100, 100, 100))
    brush.setStyle(Qt.SolidPattern)
    palette.setBrush(QPalette.Active, QPalette.Base, brush)
    brush = QBrush(QColor(50, 50, 50))
    brush.setStyle(Qt.SolidPattern)
    palette.setBrush(QPalette.Active, QPalette.Window, brush)
    brush = QBrush(QColor(0, 0, 0))
    brush.setStyle(Qt.SolidPattern)
    palette.setBrush(QPalette.Active, QPalette.Shadow, brush)
    brush = QBrush(QColor(247, 147, 30))
    brush.setStyle(Qt.SolidPattern)
    palette.setBrush(QPalette.Active, QPalette.Highlight, brush)
    brush = QBrush(QColor(77, 77, 77))
    brush.setStyle(Qt.SolidPattern)
    palette.setBrush(QPalette.Active, QPalette.AlternateBase, brush)
    brush = QBrush(QColor(255, 255, 220))
    brush.setStyle(Qt.SolidPattern)
    palette.setBrush(QPalette.Active, QPalette.ToolTipBase, brush)
    brush = QBrush(QColor(0, 0, 0))
    brush.setStyle(Qt.SolidPattern)
    palette.setBrush(QPalette.Active, QPalette.ToolTipText, brush)
    brush = QBrush(QColor(255, 255, 255))
    brush.setStyle(Qt.SolidPattern)
    palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
    brush = QBrush(QColor(80, 80, 80))
    brush.setStyle(Qt.SolidPattern)
    palette.setBrush(QPalette.Inactive, QPalette.Button, brush)
    brush = QBrush(QColor(75, 75, 75))
    brush.setStyle(Qt.SolidPattern)
    palette.setBrush(QPalette.Inactive, QPalette.Light, brush)
    brush = QBrush(QColor(62, 62, 62))
    brush.setStyle(Qt.SolidPattern)
    palette.setBrush(QPalette.Inactive, QPalette.Midlight, brush)
    brush = QBrush(QColor(25, 25, 25))
    brush.setStyle(Qt.SolidPattern)
    palette.setBrush(QPalette.Inactive, QPalette.Dark, brush)
    brush = QBrush(QColor(33, 33, 33))
    brush.setStyle(Qt.SolidPattern)
    palette.setBrush(QPalette.Inactive, QPalette.Mid, brush)
    brush = QBrush(QColor(245, 245, 245))
    brush.setStyle(Qt.SolidPattern)
    palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
    brush = QBrush(QColor(255, 255, 255))
    brush.setStyle(Qt.SolidPattern)
    palette.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
    brush = QBrush(QColor(255, 255, 255))
    brush.setStyle(Qt.SolidPattern)
    palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
    brush = QBrush(QColor(100, 100, 100))
    brush.setStyle(Qt.SolidPattern)
    palette.setBrush(QPalette.Inactive, QPalette.Base, brush)
    brush = QBrush(QColor(50, 50, 50))
    brush.setStyle(Qt.SolidPattern)
    palette.setBrush(QPalette.Inactive, QPalette.Window, brush)
    brush = QBrush(QColor(0, 0, 0))
    brush.setStyle(Qt.SolidPattern)
    palette.setBrush(QPalette.Inactive, QPalette.Shadow, brush)
    brush = QBrush(QColor(247, 147, 30))
    brush.setStyle(Qt.SolidPattern)
    palette.setBrush(QPalette.Inactive, QPalette.Highlight, brush)
    brush = QBrush(QColor(77, 77, 77))
    brush.setStyle(Qt.SolidPattern)
    palette.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush)
    brush = QBrush(QColor(255, 255, 220))
    brush.setStyle(Qt.SolidPattern)
    palette.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush)
    brush = QBrush(QColor(0, 0, 0))
    brush.setStyle(Qt.SolidPattern)
    palette.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush)
    brush = QBrush(QColor(25, 25, 25))
    brush.setStyle(Qt.SolidPattern)
    palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
    brush = QBrush(QColor(80, 80, 80))
    brush.setStyle(Qt.SolidPattern)
    palette.setBrush(QPalette.Disabled, QPalette.Button, brush)
    brush = QBrush(QColor(75, 75, 75))
    brush.setStyle(Qt.SolidPattern)
    palette.setBrush(QPalette.Disabled, QPalette.Light, brush)
    brush = QBrush(QColor(62, 62, 62))
    brush.setStyle(Qt.SolidPattern)
    palette.setBrush(QPalette.Disabled, QPalette.Midlight, brush)
    brush = QBrush(QColor(25, 25, 25))
    brush.setStyle(Qt.SolidPattern)
    palette.setBrush(QPalette.Disabled, QPalette.Dark, brush)
    brush = QBrush(QColor(33, 33, 33))
    brush.setStyle(Qt.SolidPattern)
    palette.setBrush(QPalette.Disabled, QPalette.Mid, brush)
    brush = QBrush(QColor(25, 25, 25))
    brush.setStyle(Qt.SolidPattern)
    palette.setBrush(QPalette.Disabled, QPalette.Text, brush)
    brush = QBrush(QColor(255, 255, 255))
    brush.setStyle(Qt.SolidPattern)
    palette.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
    brush = QBrush(QColor(25, 25, 25))
    brush.setStyle(Qt.SolidPattern)
    palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
    brush = QBrush(QColor(50, 50, 50))
    brush.setStyle(Qt.SolidPattern)
    palette.setBrush(QPalette.Disabled, QPalette.Base, brush)
    brush = QBrush(QColor(50, 50, 50))
    brush.setStyle(Qt.SolidPattern)
    palette.setBrush(QPalette.Disabled, QPalette.Window, brush)
    brush = QBrush(QColor(0, 0, 0))
    brush.setStyle(Qt.SolidPattern)
    palette.setBrush(QPalette.Disabled, QPalette.Shadow, brush)
    brush = QBrush(QColor(174, 174, 174))
    brush.setStyle(Qt.SolidPattern)
    palette.setBrush(QPalette.Disabled, QPalette.Highlight, brush)
    brush = QBrush(QColor(100, 100, 100))
    brush.setStyle(Qt.SolidPattern)
    palette.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush)
    brush = QBrush(QColor(255, 255, 220))
    brush.setStyle(Qt.SolidPattern)
    palette.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush)
    brush = QBrush(QColor(0, 0, 0))
    brush.setStyle(Qt.SolidPattern)
    palette.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush)
    return palette


__all__ = ("standardPalette",)
